# Generated by Django 3.0.11 on 2022-03-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrtoolkit_core', '0011_auto_20220224_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='kiosk_introduction',
            field=models.TextField(blank=True, default=''),
        ),
    ]
